# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# Also useful: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: FrontendCI

on:
  push:
    branches: [ master ]
    paths:
    - 'frontend/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'frontend/**'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: './frontend'

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ${{env.working-directory}}
    - run: npm run build --if-present
      working-directory: ${{env.working-directory}}
    - run: npm test
      working-directory: ${{env.working-directory}}
      env:
        CI: true